version: "3.9"
services:
  lob:
    container_name: lob.LobJumpStrategy.0.0.1
    image: lob/jump.strategy:0.0.1
    networks:
      - atr
    depends_on:
      - clickhouse
#    build:
#      context: .
#      dockerfile: ./docker/ms-scalping/lob.${strategy}.Dockerfile
#      args:
#        IMAGES_TAG: $IMAGES_TAG
#        BUILDER_TAG: 0.0.1
    ports:
      - '9200:9200'
    environment:
      # https://docs.doppler.com/docs/docker-compose
      - DOPPLER_TOKEN
      - TOKEN
  clickhouse:
    container_name: clickhouse
    restart: always
    networks:
      - atr
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "clickhouse:127.0.0.1"
    image: clickhouse/clickhouse-server:23.1.3.5-alpine
    ports:
      - "8123:8123"
     # - "9000:9000"
    expose:
      #- "9000" # client port
      - "8123" # client port
    volumes:
      - \\wsl$$\Ubuntu\clickhouse_data\data:/var/lib/clickhouse
      - \\wsl$$\Ubuntu\clickhouse_data\log:/var/log/clickhouse-server

networks:
  atr:
    driver: bridge
